/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mytestdemo_main_MainNativeTest */

#ifndef _Included_com_example_mytestdemo_main_MainNativeTest
#define _Included_com_example_mytestdemo_main_MainNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mytestdemo_main_MainNativeTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_mytestdemo_main_MainNativeTest_add
  (JNIEnv *env, jobject jo, jint ji1, jint ji2){
	return ji1+ji2;
};

#ifdef __cplusplus
}
#endif
#endif
