/**
 * Copyright (C) 2013-2014 Guangdong Ritu Information Systemts Co.,Ltd.
 *
 * @author qiujunwei , generated by Eclipse @date 2014-12-23
 *
 */
package com.example.mytestdemo.common;


public class Common {

    public static final String BOOT_PARAM ="cn.ritu.rtnavi.common.Common.App.BOOT_PARAM";
    //默认参数值 ：
    public static final short BOOT_PARAM_DEFAULT_VALUE = 0;
    
}
